name: AustinAmoruso
favicon: null
layout_spectrum: 0.8638955829665065
typography_spectrum: 0.12891625426709652
title: Austin Amoruso
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e4e4e'
    - '#7b7b7b'
    - '#9d9d9d'
    - '#e3e3e3'
    - '#bebebe'
  brandStrength: 0.6875
  lightness: 0.4281788105145097
  saturation: 0.28379533789120615
  rhythmicContrast: 0.685404839925468
purpose: []
